# Generated by Django 3.1.1 on 2020-11-24 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion', models.CharField(default='', max_length=10)),
                ('role', models.CharField(default='', max_length=50)),
                ('lane', models.CharField(default='', max_length=50)),
                ('spells', models.CharField(default='', max_length=50)),
                ('kills', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('deaths', models.PositiveIntegerField(default=0)),
                ('cs', models.PositiveIntegerField(default=0)),
                ('gold', models.PositiveIntegerField(default=0)),
                ('doublekills', models.PositiveIntegerField(default=0)),
                ('triplekills', models.PositiveIntegerField(default=0)),
                ('quadrakills', models.PositiveIntegerField(default=0)),
                ('pentakills', models.PositiveIntegerField(default=0)),
                ('unrealkills', models.PositiveIntegerField(default=0)),
                ('items', models.CharField(default='', max_length=50)),
                ('skill_order', models.CharField(default='', max_length=50)),
            ],
            options={
                'ordering': ['summoner'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.PositiveIntegerField(choices=[(100, 'Blue'), (200, 'Red')], default=100)),
                ('win', models.BooleanField(default=False)),
                ('barons', models.PositiveIntegerField(default=0)),
                ('towers', models.PositiveIntegerField(default=0)),
                ('inhibitors', models.PositiveIntegerField(default=0)),
                ('dragons', models.PositiveIntegerField(default=0)),
                ('riftheralds', models.PositiveIntegerField(default=0)),
                ('bans', models.CharField(max_length=100)),
                ('summoners', models.ManyToManyField(to='summoners.History')),
            ],
        ),
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summoner_id', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('puuid', models.CharField(blank=True, max_length=255)),
                ('account_id', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('revision', models.PositiveBigIntegerField(blank=True, default=0)),
                ('level', models.PositiveBigIntegerField(blank=True, default=0)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_assets.region')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('progress', models.CharField(default='', max_length=10)),
                ('summoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summoners.summoner')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=255)),
                ('timestamp', models.PositiveBigIntegerField(default=0)),
                ('duration', models.PositiveBigIntegerField(default=0)),
                ('queue', models.CharField(choices=[('RANKED_SOLO_5x5', '5v5 Ranked Solo games'), ('RANKED_FLEX_SR', '5v5 Ranked Flex games'), ('ARAM', '5v5 ARAM games')], default='', max_length=50)),
                ('teams', models.ManyToManyField(to='summoners.Team')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_points', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('veteran', models.BooleanField(default=False)),
                ('inactive', models.BooleanField(default=False)),
                ('fresh_blood', models.BooleanField(default=False)),
                ('hot_streak', models.BooleanField(default=False)),
                ('summoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summoners.summoner')),
            ],
            options={
                'ordering': ['-league_points', 'wins'],
            },
        ),
        migrations.AddField(
            model_name='history',
            name='summoner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='summoners.summoner'),
        ),
    ]
