# Generated by Django 3.1.1 on 2020-10-09 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('eun1', 'Europe Nordic & East')], max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summoner_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('puuid', models.CharField(blank=True, max_length=255)),
                ('account_id', models.CharField(blank=True, max_length=255)),
                ('icon', models.PositiveIntegerField(blank=True, default=0)),
                ('revision', models.PositiveBigIntegerField(blank=True, default=0)),
                ('level', models.PositiveBigIntegerField(blank=True, default=0)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summoners.region')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SummonerLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('queue', models.CharField(choices=[('RANKED_SOLO_5x5', '5v5 Ranked Solo games'), ('RANKED_FLEX_SR', '5v5 Ranked Flex games')], default='', max_length=50)),
                ('tier', models.CharField(choices=[('CHALLENGER', 'Challenger')], default='', max_length=50)),
                ('division', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], default='', max_length=50)),
                ('league_points', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('veteran', models.BooleanField(default=False)),
                ('inactive', models.BooleanField(default=False)),
                ('fresh_blood', models.BooleanField(default=False)),
                ('hot_streak', models.BooleanField(default=False)),
                ('summoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summoners.summoner')),
            ],
            options={
                'ordering': ['queue', 'tier', 'division', '-league_points'],
            },
        ),
        migrations.CreateModel(
            name='SummonerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=255)),
                ('queue', models.CharField(choices=[('RANKED_SOLO_5x5', '5v5 Ranked Solo games'), ('RANKED_FLEX_SR', '5v5 Ranked Flex games')], default='', max_length=50)),
                ('champion', models.PositiveIntegerField(default=0)),
                ('timestamp', models.PositiveBigIntegerField(default=0)),
                ('role', models.CharField(default='', max_length=50)),
                ('lane', models.CharField(default='', max_length=50)),
                ('summoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summoners.summoner')),
            ],
            options={
                'ordering': ['summoner', '-timestamp'],
            },
        ),
    ]
