# Generated by Django 3.1.1 on 2020-11-24 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=10)),
                ('icon', models.ImageField(upload_to='championicons/')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=10)),
                ('icon', models.ImageField(upload_to='itemicons/')),
                ('description', models.CharField(max_length=1000)),
                ('cost', models.PositiveIntegerField(default=0)),
                ('sell', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.CharField(choices=[('RANKED_SOLO_5x5', '5v5 Ranked Solo games'), ('RANKED_FLEX_SR', '5v5 Ranked Flex games'), ('ARAM', '5v5 ARAM games')], default='', max_length=50)),
                ('tier', models.CharField(choices=[('DIAMOND', 'Diamond'), ('PLATINUM', 'Platinum'), ('GOLD', 'Gold'), ('SILVER', 'Silver'), ('BRONZE', 'Bronze'), ('IRON', 'Iron')], default='', max_length=50)),
                ('division', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], max_length=50)),
                ('icon', models.ImageField(upload_to='leagueicons/')),
            ],
            options={
                'ordering': ['queue', 'tier', 'division'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('br1', 'Brazil'), ('eun1', 'Europe Nordic & East'), ('euw1', 'Europe West'), ('jp1', 'Japan'), ('la1', 'Latin America North'), ('la2', 'Latin America South'), ('na1', 'North America'), ('oc1', 'Oceania'), ('ru', 'Russia'), ('tr1', 'Turkey'), ('kr', 'Republic of Korea')], max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_version', models.CharField(default='', max_length=10, unique=True)),
                ('regions', models.ManyToManyField(to='game_assets.Region')),
            ],
        ),
        migrations.CreateModel(
            name='SummonerIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10)),
                ('icon', models.ImageField(upload_to='summonericons/')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_assets.version')),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('key', models.CharField(blank=True, max_length=10)),
                ('icon', models.ImageField(upload_to='spellicons/')),
                ('keybind', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=1000)),
                ('cost', models.CharField(blank=True, max_length=100)),
                ('cooldown', models.CharField(blank=True, max_length=100)),
                ('spell_range', models.CharField(blank=True, max_length=100)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_assets.version')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('TOP', 'Top'), ('MID', 'Mid'), ('JUNGLE', 'Jungle'), ('BOT', 'Bot'), ('SUPPORT', 'Support')], max_length=10)),
                ('icon', models.ImageField(upload_to='positionicons/')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_assets.league')),
            ],
        ),
    ]
